apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
  labels:
    app: nextcloud
data:
  POSTGRES_DB: "nextcloud"
  POSTGRES_USER: "nextcloud"
  POSTGRES_HOST: "db"
  REDIS_HOST: "redis"
  REDIS_HOST_PORT: "6379"
  OVERWRITEPROTOCOL: "https"
  NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.local"
  PHP_MEMORY_LIMIT: "512M"
  PHP_UPLOAD_LIMIT: "16G"
